{{- if .Values.generateBasicAuth }}
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "openfaas.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: gateway
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": "pre-install"
data:
  {{- if .Values.basic_auth_user }}
  basic-auth-user: {{ .Values.basic_auth_user | b64enc | quote }}
  {{- else }}
  basic-auth-user: {{ "admin" | b64enc | quote }}
  {{- end }}
  # kubectl -n openfaas get secret basic-auth -o jsonpath="{.data.basic-auth-password}" | base64 --decode
  {{- if .Values.basic_auth_pass }}
  basic-auth-password: {{ .Values.basic_auth_pass | b64enc | quote }}
  {{- else }}
  basic-auth-password: {{ randAlphaNum 12 | b64enc | quote }}
  {{- end }}
{{- end }}
